name: Antithesis

on:
  workflow_call:
    secrets:
      ANTITHESIS_KEY:
        required: true

  # Just for testing - remove when done.
  pull_request:
    branches:
      - 'main'
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./tools/antithesis/scripts/build.sh ${{ github.sha }}
      - run: ./tools/antithesis/scripts/push.sh ${{ github.sha }}
        env:
          ANTITHESIS_KEY: ${{ secrets.ANTITHESIS_KEY }}
