name: CI Pipeline

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'main'

  # Run on Merge queue
  merge_group:

  # Run CI for any PRs that target 'main' when they are opened or updated.
  pull_request:
    branches:
      - 'main'
    types:
      - opened
      - synchronize

jobs:
  client-dotnet:
    uses: ./.github/workflows/clients-dotnet.yml
    secrets:
      NUGET_KEY: ${{ secrets.NUGET_KEY }}
