name: Clients Pipeline

concurrency:
  group: clients-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  # Run CI for any PRs that target 'main' when they are opened or updated.
  pull_request:
    branches:
      - 'main'
    types:
      - opened
      - synchronize

  workflow_call:

jobs:
  client-dotnet:
    uses: ./.github/workflows/clients-dotnet.yml
  client-go:
    uses: ./.github/workflows/clients-go.yml
  client-java:
    uses: ./.github/workflows/clients-java.yml
  client-node:
    uses: ./.github/workflows/clients-node.yml
  clients-pipeline:
    needs:
      - client-dotnet
      - client-go
      - client-java
      - client-node

    runs-on: ubuntu-latest
    steps:
      - name: All Client CI Jobs Passed
        working-directory: ./
        run: exit 0
